package com.algods.leetcode.september;
/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */
import java.util.*;
public class FindStringDifference {
	public char findTheDifference(String s, String t) {
        HashSet<Character> hs= new HashSet<>();
        for(char c: s.toCharArray()) hs.add(c);
        for(char c: t.toCharArray()) {if(!hs.contains(c)) return c;}
		return 0;
    }
	public static void main(String[] args) {
		FindStringDifference instance= new FindStringDifference();
		System.out.println(instance.findTheDifference("abcd", "abcde"));
		System.out.println(instance.findTheDifference("a", "aa"));
	}

}
